import type { NextPage } from "next";
import Head from "next/head";
import { AboutSection, IntroSection, MintSection } from "view/landing";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>CRYPTID</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IntroSection />
      <AboutSection />
      <MintSection />
    </div>
  );
};

export default Home;
